### PR TITLE
Register as a formatter

### PR DESCRIPTION
**Pull request by lennybacon**
As I described in #5, it would be nice to have the extension registered as a language formatter for SQL. Here it is.

### CODE REVIEW

**Comment by JDeeth** [comment]
This is tremendously useful - thanks WSR and thanks Lenny for taking it just a bit further!

**Comment by lennybacon** [comment]
@dannyrich The repo is inactive for quite a while. Do you, as the initial committer, still have access?

**Comment by dannyrich** [comment]
I do have access. I'll take a look at the code and merge when possible. Thanks @lennybacon for the improvement.

**Comment by lennybacon** [comment]
@dannyrich Thank you! Let me know If you need anything.

**Review by dannyrich — APPROVED** [review]

**Comment by JDeeth** [comment]
Folks, is there any extra steps needed to make this available to the marketplace in Azure Data Studio? Mine still shows as 0.1.0 and I've edited the code myself to apply Lenny's changes. I'm about to do an intro-to-SQL workshop for my colleagues and I hoped to have "step 1: install Azure Data Studio, step 2: install Poor SQL Formatter extension, step 3: life is beautiful now" as the preparation steps...

**Comment by lennybacon** [comment]
@dannyrich did not publish any version ever to the marketplace as far as I know. You can easily install the vsix after you downloaded it.
But… the VS Gallery would be nice 👍

**Pull request merged**
